# Generated by Django 5.0.7 on 2024-07-22 14:43

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('zip_code', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'cities',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='PropertyFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('icon', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='PropertyTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='property/images/')),
                ('name', models.CharField(max_length=255)),
                ('price_start', models.PositiveIntegerField(default=0)),
                ('price_end', models.PositiveIntegerField(default=0)),
                ('property_id', models.CharField(blank=True, max_length=255, null=True)),
                ('content', tinymce.models.HTMLField()),
                ('address', models.CharField(max_length=1000)),
                ('lat', models.FloatField(null=True)),
                ('long', models.FloatField(null=True)),
                ('slug', models.SlugField(unique=True)),
                ('youtube_video_id', models.CharField(blank=True, help_text="Don't place video links here use youtube Id like ", max_length=100, null=True)),
                ('price_list_file', models.FileField(blank=True, help_text='Make sure to upload pdf file.', null=True, upload_to='property/files/price_lists/')),
                ('floor_map_file', models.FileField(blank=True, help_text='Make sure to upload pdf file.', null=True, upload_to='property/files/floor_maps/')),
                ('floor_payment_image', models.ImageField(blank=True, null=True, upload_to='property/images/floor_payment_plans/')),
                ('floor_payment_file', models.ImageField(blank=True, null=True, upload_to='property/images/floor_payment_files/')),
                ('floor_payment_description', models.TextField(blank=True, null=True)),
                ('floor_design_image', models.ImageField(blank=True, null=True, upload_to='property/images/floor_payment_plans/')),
                ('floor_design_file', models.ImageField(blank=True, null=True, upload_to='property/images/floor_payment_files/')),
                ('floor_design_description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('o', 'Open'), ('c', 'Close')], max_length=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admins.city')),
                ('features', models.ManyToManyField(to='admins.propertyfeature')),
                ('tags', models.ManyToManyField(to='admins.propertytag')),
                ('property_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admins.propertytype')),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='PropertyFloorPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_start', models.FloatField(default=0, help_text='Size in sq.ft')),
                ('size_end', models.FloatField(default=0, help_text='Size in sq.ft')),
                ('price_start', models.FloatField(default=0, help_text='Price in Pakistani Rupees')),
                ('price_end', models.FloatField(default=0, help_text='Price in Pakistani Rupees')),
                ('bed_rooms', models.PositiveIntegerField(default=1)),
                ('bath_rooms', models.PositiveIntegerField(default=1)),
                ('image', models.ImageField(blank=True, null=True, upload_to='property/images/floor_plans/images/')),
                ('file', models.ImageField(blank=True, null=True, upload_to='property/images/floor_plans/files/')),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admins.property')),
            ],
            options={
                'ordering': ['property', 'bed_rooms'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property/images/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admins.property')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='PropertyVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_video_id', models.CharField(blank=True, help_text="Don't place video links here use youtube Id like ", max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admins.property')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admins.state'),
        ),
    ]
